version: '3.3'
services:
  mysql5.5:
    image: mysql:5.5
    container_name: ${MYSQL_CONTAINER_NAME_PREFIX}5.5
    restart: always
    environment:
       - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
       - TZ=${TIMEZONE}
    ports:
      - '3355:3306'
    expose:
      - '3306'
    volumes:
      - ./data/${MYSQL_CONTAINER_NAME_PREFIX}5.5/:/var/lib/mysql

  mysql5.7:
    image: mysql:5.7
    container_name: ${MYSQL_CONTAINER_NAME_PREFIX}5.7
    restart: always
    environment:
       - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
       - TZ=${TIMEZONE}
    ports:
      - '3357:3306'
    expose:
      - '3306'
    volumes:
      - ./data/${MYSQL_CONTAINER_NAME_PREFIX}5.7/:/var/lib/mysql

  mysql8.0:
    image: mysql:8.0
    container_name: ${MYSQL_CONTAINER_NAME_PREFIX}8.0
    command: mysqld --default-authentication-plugin=mysql_native_password
    ports:
      - 3380:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - TZ=${TIMEZONE}
    volumes:
      - ./data/${MYSQL_CONTAINER_NAME_PREFIX}8.0/:/var/lib/mysql

  mariadb:
    image: mariadb
    # Set max_allowed_packet to 256M (or any other value)
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./data/mariadb/:/var/lib/mysql
    ports:
      - "3310:3306"
